#!/bin/bash
#
#  Linux Rom Kitchen Build script
#
#  Copyright (C) 2007-2008 Pau Oliva Fora - <pof@eslack.org>
#
#  This program is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by the
#  Free Software Foundation; either version 3 of the License, or (at your
#  opinion) any later version. See <http://www.gnu.org/licenses/gpl.html>
#

TOOLS="/usr/share/LinuxRomKitchen/"
CURRENTDIR=`pwd`

## SYS, ROM & Packages folders must exist
if ! [ -d SYS ]; then
	echo "ERROR: SYS folder doesn't exist, run lrk-extract first"
	exit 1
fi

if ! [ -d ROM ]; then
	echo "ERROR: ROM folder doesn't exist, run lrk-extract first"
	exit 1
fi

if ! [ -d Packages ]; then
	echo "Warning: Packages folder doesn't exist, creating an empty one"
	echo "No custom packages will be added to this rom."
	mkdir Packages
fi

echo "$CURRENTDIR" |grep " " 1>/dev/null
if [ $? != 1 ]; then
	echo "ERROR: Sorry, the current work directory can't contain spaces: $CURRENTDIR"
	exit 1
fi

if ! [ -e $TOOLS ]; then
	echo "ERROR: $TOOLS does not exist"
	exit 1
fi

if [ "`which wine`" = "" ]; then
	echo "ERROR: wine is not installed"
	exit 1
fi

if [ "`which lcab`" = "" ]; then
	echo "ERROR: lcab is not installed"
	echo "Hint: http://lcab.move-to-cork.com/"
	exit 1
fi

if [ "`which sofbuild`" = "" ]; then
	echo "ERROR: sofbuild is not installed"
	echo "Hint: Make sure you have installed latest version of htc-flasher"
	exit 1
fi

if [ "`which nbsplit`" = "" ]; then
        echo "ERROR: nbsplit is not installed"
        echo "Hint: Make sure you have installed latest version of htc-flasher"
        exit 1
fi

rm -rf ~/.lrk/ 2>/dev/null
mkdir -p ~/.lrk/Temp/
cd ~/.lrk/Temp
mkdir Packages
cd Packages

find "$CURRENTDIR/SYS/" -name "*.rgu" -exec cp {} . \;
find "$CURRENTDIR/ROM/" -name "*.rgu" -exec cp {} . \;
find "$CURRENTDIR/Packages/" -name "*.rgu" -exec cp {} . \;

find "$CURRENTDIR/SYS/" -name "*.dsm" -exec cp {} . \;
find "$CURRENTDIR/ROM/" -name "*.dsm" -exec cp {} . \;
find "$CURRENTDIR/Packages/" -name "*.dsm" -exec cp {} . \;

# rgucomp.exe needs cereg400.dll to mount the hives
export _FLATRELEASEDIR=.
wine $TOOLS/rgucomp.exe -b
mv boot.hv ..
mv boot.rgu ..

if [ $? != 0 ]; then
	echo "ERROR: rgucomp failed. Make sure have installed .net CF 2.0 in wine"
	echo "Hint:"
	echo "   wget http://kegel.com/wine/winetricks"
	echo "   sh winetricks corefonts dotnet20 vcrun2005"
	echo
	exit 1
fi

lcab -n * ../packages.cab.pkg
cd ..
mv packages.cab.pkg Packages/

if [ $? != 0 ]; then
	echo "ERROR: Problem creating packages.cab.pkg"
	exit 1
fi

# here we need to regenerate the packages.sof
sofbuild Packages/
wine $TOOLS/rgucomp.exe

### we need to end up only with 1 "dump" folder in Temp
mkdir dump
cd dump
cp -R $CURRENTDIR/ROM/XIP/* .
for f in `/bin/ls "$CURRENTDIR/SYS/"` ; do
	cp -R $CURRENTDIR/SYS/${f}/* .
done

rm -rf default.hv packages.sof user.hv

if [ $? != 0 ]; then
	echo "ERROR: Some problem occurred when creating the dump folder"
	exit 1
fi

# return to Temp
cd ..
cp boot.hv boot.rgu default.hv packages.sof user.hv dump/
if [ $? != 0 ]; then
	echo "ERROR: Some problem occurred when creating the dump folder"
	exit 1
fi
chmod 444 dump/default.hv dump/packages.sof dump/user.hv

### createROM
cd ..
cd Temp

cp "$CURRENTDIR/ROM/OS.nb" .
if [ $? != 0 ]; then
	echo "ERROR: OS.nb not found in ROM"
	exit 1
fi

nbsplit -kaiser ./OS.nb |tee log.dump 2>/dev/null
wine $TOOLS/ImgfsFromNb.exe OS.nb.payload imgfs.bin |tee log.dump 2>/dev/null
wine $TOOLS/ImgfsFromDump.exe imgfs.bin imgfs-new.bin |tee log.dump 2>/dev/null
wine $TOOLS/ImgfsToNb.exe imgfs-new.bin os.nb.payload os-new.nb.payload |tee log.dump 2>/dev/null
wine $TOOLS/NBMerge.exe -kaiser os-new.nb |tee log.dump 2>/dev/null

echo "Cleaning up..."
mv os-new.nb "$CURRENTDIR"
if [ $? != 0 ]; then
	echo "ERROR: Can't create os-new.nb"
	exit 1
fi
cd "$CURRENTDIR"
rm -rf ~/.lrk/ 2>/dev/null

echo "Done!"
